spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 200
        min-idle: 50
        max-idle: 100
        max-wait: 10000

logging:
  level:
    org.springframework.web: INFO
    com.example.weixin.cp: DEBUG
    com.example.weixin: DEBUG